#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  {
    {KC_GESC, KC_TAB, KC_Q, KC_W, KC_1, KC_2, KC_3, KC_E},
    {KC_Z, KC_LGUI, KC_S, KC_LCTRL, KC_NONUS_BSLASH, KC_LSHIFT, KC_A, KC_CAPSLOCK},
    {KC_4, KC_R, KC_5, KC_T, KC_6, KC_7, KC_Y, KC_U},
    {KC_B, KC_G, KC_V, KC_C, KC_LALT, KC_X, KC_F, KC_D},
    {KC_8, KC_I, KC_9, KC_0, KC_MINUS, KC_O, KC_P, KC_LBRACKET},
    {KC_L, KC_COMMA, KC_M, KC_SPACE, KC_N, KC_K, KC_J, KC_H},
    {KC_EQUAL, KC_BSPACE, KC_BSPACE, KC_HOME, KC_RBRACKET, KC_BSLASH, KC_NO, KC_NO},
    {KC_ENTER, KC_LEFT, MO(1), KC_RALT, KC_QUOTE, KC_SLASH, KC_DOT, KC_SCOLON},
    {KC_PGUP, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_PGDOWN, KC_END, KC_RIGHT, KC_DOWN, KC_UP, KC_RSHIFT},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO}
  },
  {
    {KC_GRAVE, KC_TRNS, KC_BTN1, KC_MS_U, KC_F1, KC_F2, KC_F3, KC_BTN2},
    {KC_TRNS, KC_TRNS, KC_MS_D, KC_TRNS, KC_TRNS, KC_TRNS, KC_MS_L, KC_TRNS},
    {KC_F4, KC_TRNS, KC_F5, KC_TRNS, KC_F6, KC_F7, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_CALC, KC_TRNS, KC_TRNS, KC_TRNS, KC_MS_R},
    {KC_F8, KC_TRNS, KC_F9, KC_F10, KC_F11, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_VOLD, KC_MUTE, KC_TRNS, MAGIC_TOGGLE_NKRO, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_F12, KC_DELETE, KC_DELETE, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO},
    {KC_TRNS, KC_HOME, KC_TRNS, KC_TRNS, KC_MPLY, KC_MNXT, KC_VOLU, KC_MPRV},
    {KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_TRNS, KC_INSERT, KC_END, KC_PGDOWN, KC_PGUP, KC_TRNS},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO}
  },
};
