#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = 
{
  {
    {QK_GESC, LT(2, KC_TAB), KC_LSFT, KC_NO, LGUI_T(KC_BSLS), KC_BSPC, KC_ENTER, LT(3, KC_RIGHT)},
    {KC_Q, KC_A, KC_Z, KC_LCTL, KC_P, KC_SCLN, RSFT_T(KC_UP), KC_NO},
    {KC_W, KC_S, KC_X, KC_LALT, KC_O, KC_L, KC_DOT, KC_DOWN},
    {KC_E, KC_D, KC_C, KC_NO, KC_I, KC_K, KC_COMMA, KC_LEFT},
    {KC_R, KC_F, KC_V, LT(1, KC_SPACE), KC_U, KC_J, KC_M, KC_NO},
    {KC_T, KC_G, KC_B, KC_SPACE, KC_Y, KC_H, KC_N, KC_SPACE}
  },
  {
    {KC_GRAVE, KC_TRNS, KC_TRNS, KC_NO, KC_MINUS, KC_EQUAL, KC_TRNS, KC_TRNS},
    {KC_1, KC_TRNS, KC_TRNS, KC_TRNS, KC_0, KC_SCLN, KC_TRNS, KC_NO},
    {KC_2, KC_TRNS, KC_TRNS, KC_TRNS, KC_9, KC_TRNS, KC_SLASH, KC_TRNS},
    {KC_3, KC_BTN1, KC_MS_L, KC_NO, KC_8, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_4, KC_MS_U, KC_MS_D, KC_TRNS, KC_7, KC_RBRC, KC_TRNS, KC_NO},
    {KC_5, KC_BTN2, KC_MS_R, KC_WSCH, KC_6, KC_LBRC, KC_TRNS, KC_TRNS}
  },
  {
    {KC_CAPS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_PSCR, KC_DELETE, KC_PAUSE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO},
    {KC_PGUP, KC_PGDN, KC_SCRL, KC_TRNS, KC_TRNS, KC_TRNS, KC_RGUI, KC_RCTL},
    {KC_HOME, KC_END, KC_F4, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_RALT},
    {KC_F2, KC_F5, LGUI(KC_V), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO},
    {KC_WH_U, KC_WH_D, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS}
  },
  {
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_F11, KC_F12, KC_MPLY, KC_TRNS},
    {KC_F1, KC_TRNS, KC_TRNS, KC_TRNS, KC_F10, KC_TRNS, KC_VOLU, KC_NO},
    {KC_F2, KC_TRNS, KC_TRNS, KC_TRNS, KC_F9, KC_TRNS, KC_MNXT, KC_VOLD},
    {KC_F3, KC_TRNS, KC_TRNS, KC_NO, KC_F8, KC_TRNS, KC_MPRV, KC_MUTE},
    {KC_F4, KC_TRNS, KC_TRNS, KC_TRNS, KC_F7, KC_TRNS, KC_TRNS, KC_NO},
    {KC_F5, KC_TRNS, KC_TRNS, KC_TRNS, KC_F6, KC_TRNS, KC_TRNS, KC_TRNS}
  }
};



